create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key,
  email text not null,
  nombre_completo text not null,
  telefono text null,
  direccion text null,
  role text not null default 'socio',
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  nombre text not null,
  parent_id bigint null references public.categories(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.books (
  id bigint generated by default as identity primary key,
  isbn text not null unique,
  titulo text not null,
  autor text not null,
  editorial text not null,
  anio_publicacion integer not null,
  idioma text not null,
  num_paginas integer not null,
  categoria_id bigint not null references public.categories(id),
  sinopsis text not null,
  precio_fisico numeric not null,
  precio_digital numeric not null,
  imagenes text[] not null default '{}',
  calificacion_promedio numeric not null default 0,
  stock_fisico integer not null,
  peso_gramos numeric not null,
  dimensiones text not null,
  ubicacion_bodega text not null,
  disponible_prestamo boolean not null default true,
  url_digital_preview text null,
  url_libro_completo text null,
  es_audiolibro boolean not null default false,
  duracion_minutos integer null,
  created_at timestamptz not null default now()
);

create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null,
  libro_id bigint not null references public.books(id),
  cantidad integer not null,
  precio_unitario numeric not null,
  tipo_item text not null,
  created_at timestamptz not null default now(),
  unique (usuario_id, libro_id, tipo_item)
);

create table if not exists public.ordenes (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null,
  total numeric not null,
  metodo_entrega text not null,
  estado_pago text not null default 'pendiente',
  created_at timestamptz not null default now()
);

create table if not exists public.orden_detalles (
  id bigint generated by default as identity primary key,
  orden_id bigint not null references public.ordenes(id) on delete cascade,
  libro_id bigint not null references public.books(id),
  cantidad integer not null,
  precio_unitario numeric not null,
  tipo_item text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.pagos (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null,
  orden_id bigint not null references public.ordenes(id) on delete cascade,
  monto numeric not null,
  metodo_pago text not null,
  estado text not null default 'pendiente',
  created_at timestamptz not null default now()
);

create table if not exists public.logs_inventario (
  id bigint generated by default as identity primary key,
  libro_id bigint not null references public.books(id),
  cantidad_ingresada integer not null,
  motivo text not null,
  usuario_admin_id uuid not null,
  created_at timestamptz not null default now()
);

create table if not exists public.sucursales_biblioteca (
  id bigint generated by default as identity primary key,
  nombre text not null,
  direccion text not null,
  lat numeric not null,
  lng numeric not null,
  created_at timestamptz not null default now()
);

create table if not exists public.despachos (
  id bigint generated by default as identity primary key,
  orden_id bigint not null references public.ordenes(id) on delete cascade,
  codigo_seguimiento text not null unique,
  direccion_destino text not null,
  sucursal_retiro_id bigint null references public.sucursales_biblioteca(id),
  estado_envio text not null default 'en_preparacion',
  created_at timestamptz not null default now()
);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  nombre text not null,
  email text not null,
  telefono text null,
  asunto text not null,
  mensaje text not null,
  status text not null default 'received',
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  tipo text not null,
  canal text not null,
  to_email text null,
  to_whatsapp text null,
  subject text not null,
  body text not null,
  status text not null,
  error text null,
  created_at timestamptz not null default now()
);
