create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  libro_id bigint not null references public.books(id) on delete cascade,
  usuario_id uuid not null,
  rating integer not null check (rating >= 1 and rating <= 5),
  comentario text not null,
  estado text not null default 'pending',
  motivo text null,
  created_at timestamptz not null default now(),
  unique (usuario_id, libro_id)
);

create index if not exists reviews_libro_id_idx on public.reviews(libro_id);
create index if not exists reviews_estado_idx on public.reviews(estado);
