create table if not exists public.wishlist_items (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null,
  libro_id bigint not null references public.books(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (usuario_id, libro_id)
);

create index if not exists wishlist_usuario_idx on public.wishlist_items(usuario_id);
create index if not exists wishlist_libro_idx on public.wishlist_items(libro_id);

alter table public.wishlist_items enable row level security;

create policy "wishlist_select_owner"
on public.wishlist_items for select
to authenticated
using (usuario_id = auth.uid() or public.is_admin());

create policy "wishlist_insert_owner"
on public.wishlist_items for insert
to authenticated
with check (usuario_id = auth.uid() or public.is_admin());

create policy "wishlist_delete_owner"
on public.wishlist_items for delete
to authenticated
using (usuario_id = auth.uid() or public.is_admin());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'book-covers',
  'book-covers',
  true,
  5242880,
  array['image/png', 'image/jpeg', 'image/webp', 'image/gif']
)
on conflict (id) do nothing;

create policy "book_covers_public_read"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'book-covers');

create policy "book_covers_admin_insert"
on storage.objects for insert
to authenticated
with check (bucket_id = 'book-covers' and public.is_admin());

create policy "book_covers_admin_update"
on storage.objects for update
to authenticated
using (bucket_id = 'book-covers' and public.is_admin())
with check (bucket_id = 'book-covers' and public.is_admin());

create policy "book_covers_admin_delete"
on storage.objects for delete
to authenticated
using (bucket_id = 'book-covers' and public.is_admin());
